[colors.primary]
background = '#0e141c'
foreground = '#dde2ee'

[colors.selection]
text = '#dde2ee'
background = '#004882'

[colors.cursor]
text = '#0e141c'
cursor = '#a2c9ff'

[colors.normal]
black   = '#0e141c'
red     = '#e64c46'
green   = '#71d66e'
yellow  = '#dbd17b'
blue    = '#5684c6'
magenta = '#879ebf'
cyan    = '#a2c9ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f5f'
green   = '#88e086'
yellow  = '#e8df97'
blue    = '#add7ff'
magenta = '#487ea3'
cyan    = '#6578ac'
white   = '#ffffff'
