#!/bin/bash

OUTPUT_DIR="$HOME/Pictures/Screenshots"

if [[ ! -d "$OUTPUT_DIR" ]]; then
  mkdir -p "$OUTPUT_DIR"
fi

FILENAME="$OUTPUT_DIR/screenshot-$(date +'%Y-%m-%d_%H-%M-%S').png"

pkill slurp || hyprshot -m ${1:-region} --raw | \
  DBUS_SESSION_BUS_ADDRESS=/dev/null satty --filename - \
    --output-filename "$FILENAME" \
    --early-exit \
    --actions-on-enter save-to-clipboard \
    --save-after-copy \
    --copy-command 'wl-copy'