#!/bin/bash

OUTPUT_DIR="$HOME/Pictures/Screenshots"

if [[ ! -d "$OUTPUT_DIR" ]]; then
  mkdir -p "$OUTPUT_DIR"
fi

FILENAME="$OUTPUT_DIR/screenshot-$(date +'%Y-%m-%d_%H-%M-%S').png"

pkill slurp || hyprshot -m ${1:-region} --raw | tee "$FILENAME" | \
  satty --filename - \
    --early-exit \
    --disable-notifications \
    --actions-on-enter save-to-clipboard \
    --copy-command 'wl-copy'

