#!/usr/bin/env bash
# snappy-noctalia.sh
# Syncs snappy-switcher theme with the current Noctalia color scheme.
#
# Hook argument from Noctalia:
#   $1 = theme mode ("dark" or "light")
#
# Setup: In Noctalia settings → Hooks, add:
#   hooks.colorGeneration = "/path/to/snappy-noctalia.sh $1"

COLORS_JSON="$HOME/.config/noctalia/colors.json"
SNAPPY_THEME="$HOME/.config/snappy-switcher/themes/noctalia.ini"
SNAPPY_CONFIG="$HOME/.config/snappy-switcher/config.ini"

if [ ! -f "$COLORS_JSON" ]; then
    echo "[snappy] Error: $COLORS_JSON not found" >&2
    exit 1
fi

if [ ! -f "$SNAPPY_CONFIG" ]; then
    echo "[snappy] Error: $SNAPPY_CONFIG not found. Run 'snappy-install-config' first." >&2
    exit 1
fi

NOCTALIA_THEME="${1:-light}"

# ── Generate theme file via Python ──────────────────────────────────────────
python3 - "$NOCTALIA_THEME" "$SNAPPY_THEME" << 'PYEOF'
import json, os, sys, colorsys

theme_mode = sys.argv[1]   # "dark" or "light"
out_path   = sys.argv[2]

with open(os.path.expanduser("~/.config/noctalia/colors.json")) as f:
    c = json.load(f)

def hex_to_rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

def rgb_to_hex(r, g, b):
    return f"#{int(r):02x}{int(g):02x}{int(b):02x}"

def adjust_lightness(hex_color, delta):
    """Shift HLS lightness by delta (+= lighten, -= darken), clamped to [0,1]."""
    r, g, b = hex_to_rgb(hex_color)
    h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    l = max(0.0, min(1.0, l + delta))
    r2, g2, b2 = colorsys.hls_to_rgb(h, l, s)
    return rgb_to_hex(r2 * 255, g2 * 255, b2 * 255)

def aa(hex_color, alpha):
    """Append 2-char hex alpha suffix to a #RRGGBB string."""
    return f"{hex_color}{alpha}"

# ── Pull roles from noctalia colors.json ────────────────────────────────────
primary         = c.get("mPrimary",          "#1ea995")
on_primary      = c.get("mOnPrimary",        "#030404")
surface         = c.get("mSurface",          "#e2e9e8")
surface_variant = c.get("mSurfaceVariant",   "#d6e0df")
on_surface      = c.get("mOnSurface",        "#181b1a")
on_surface_var  = c.get("mOnSurfaceVariant", "#505857")

# ── Derive selected-card shade from surface brightness ──────────────────────
r, g, b = hex_to_rgb(surface)
luminance = (r * 299 + g * 587 + b * 114) / 1000

if luminance > 128:
    # Light theme → darken card_bg slightly for the selected state
    card_selected = adjust_lightness(surface_variant, -0.1)
else:
    # Dark theme → lighten card_bg slightly for the selected state
    card_selected = adjust_lightness(surface_variant, +0.1)

# ── Write theme file ─────────────────────────────────────────────────────────
content = f"""\
# Noctalia — auto-generated by snappy-noctalia.sh
# Mode: {theme_mode}  |  DO NOT EDIT — regenerated on every theme change

[colors]
background       = {aa(surface, 'ee')}
card_bg          = {aa(surface_variant, 'ff')}
card_selected    = {aa(card_selected, 'ff')}
border_color     = {aa(primary, 'ff')}
text_color       = {aa(on_surface, 'ff')}
subtext_color    = {aa(on_surface_var, 'ff')}
bundle_bg        = {aa(surface_variant, 'cc')}
badge_bg         = {aa(primary, 'ff')}
badge_text_color = {aa(on_primary, 'ff')}
"""

os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w") as f:
    f.write(content)

print(f"[snappy] theme written → {out_path}")
print(f"  primary={primary}  surface={surface}  on_surface={on_surface}")
PYEOF

# ── Patch config.ini ─────────────────────────────────────────────────────────
# Point to our generated theme and match hyprland's decoration settings
# (border_size = 3, rounding = 0 from decorations.conf)
sed -i "s/^name = .*/name = noctalia.ini/"       "$SNAPPY_CONFIG"
sed -i "s/^border_width = .*/border_width = 3/"  "$SNAPPY_CONFIG"
sed -i "s/^corner_radius = .*/corner_radius = 0/" "$SNAPPY_CONFIG"

# ── Restart daemon to pick up the new theme ───────────────────────────────────
if pgrep -x snappy-switcher > /dev/null; then
    snappy-switcher quit
    sleep 0.3
fi
snappy-switcher --daemon &
disown

echo "[snappy] daemon restarted with noctalia theme ($NOCTALIA_THEME)"
