$primary = rgb(89c022)
$surface = rgb(e9f1da)
$secondary = rgb(3ca329)
$error = rgb(ad4d3b)
$tertiary = rgb(2d3e86)
$surface_lowest = rgb(f6f9f0)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
