[colors]
draw_bold_text_with_bright_colors = true

# Pywal colors - this section will be replaced by update script
[colors.primary]
background = "#0e1122"
foreground = "#c2c3c7"

[colors.normal]
black = "#0e1122"
red = "#5E6175"
green = "#64677B"
yellow = "#717589"
blue = "#837D8E"
magenta = "#7D8197"
cyan = "#9895A6"
white = "#c2c3c7"

[colors.bright]
black = "#5e6172"
red = "#5E6175"
green = "#64677B"
yellow = "#717589"
blue = "#837D8E"
magenta = "#7D8197"
cyan = "#9895A6"
white = "#c2c3c7"
