[colors.primary]
background = "#0f0f23"
foreground = "#c3c3c8"

[colors.cursor]
text = "#0f0f23"
cursor = "#c3c3c8"

[colors.vi_mode_cursor]
text = "#0f0f23"
cursor = "#c3c3c8"

[colors.search.matches]
foreground = "#0f0f23"
background = "#c3c3c8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5e5e74"
background = "#c3c3c8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0f0f23"
red = "#62677B"
green = "#6F758A"
yellow = "#857C90"
blue = "#7C849D"
magenta = "#8993AF"
cyan = "#9FAFD8"
white = "#c3c3c8"

[colors.bright]
black = "#5e5e74"
red = "#62677B"
green = "#6F758A"
yellow = "#857C90"
blue = "#7C849D"
magenta = "#8993AF"
cyan = "#9FAFD8"
white = "#c3c3c8"

[colors.dim]
black = "#c3c3c8"
red = "#62677B"
green = "#8993AF"
yellow = "#857C90"
blue = "#7C849D"
magenta = "#6F758A"
cyan = "#9FAFD8"
white = "#5e5e74"

