[colors]
background = '#0f0f238e'
black = '#0f0f23'
blue = '#62677B'
cursor = '#c3c3c8'
cyan = '#6F758A'
foreground = '#c3c3c8'
green = '#857C90'
magenta = '#7C849D'
red = '#8993AF'
tabs = '#c3c3c8'
tabs-active = '#9FAFD8'
white = '#c3c3c8'
yellow = '#c3c3c8'
dim-black = '#0f0f238e'
dim-blue = '#62677B8e'
dim-cyan = '#6F758A8e'
dim-foreground = '#c3c3c88e'
dim-green = '#857C908e'
dim-magenta = '#7C849D8e'
dim-red = '#8993AF8e'
dim-white = '#9FAFD88e'
dim-yellow = '#c3c3c88e'
light-black = '#62677B'
light-blue = '#6F758A'
light-cyan = '#857C90'
light-foreground = '#7C849D'
light-green = '#8993AF'
light-magenta = '#9FAFD8'
light-red = '#c3c3c8'
light-white = '#62677B'
light-yellow = '#6F758A'
