--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kalon/Pictures/Wallpaper-Collection/Wallpapers/tree-stump.jpg"

-- Special
background="#0f0f23"
foreground="#c3c3c8"
cursor="#c3c3c8"

-- Colors
color0="#0f0f23"
color1="#62677B"
color2="#6F758A"
color3="#857C90"
color4="#7C849D"
color5="#8993AF"
color6="#9FAFD8"
color7="#c3c3c8"
color8="#5e5e74"
color9="#62677B"
color10="#6F758A"
color11="#857C90"
color12="#7C849D"
color13="#8993AF"
color14="#9FAFD8"
color15="#c3c3c8"
