# Shell variables
# Generated by 'wal'
wallpaper="/home/kalon/Pictures/Wallpaper-Collection/Wallpapers/tree-stump.jpg"

# Special
background='#0f0f23'
foreground='#c3c3c8'
cursor='#c3c3c8'

# Colors
color0='#0f0f23'
color1='#62677B'
color2='#6F758A'
color3='#857C90'
color4='#7C849D'
color5='#8993AF'
color6='#9FAFD8'
color7='#c3c3c8'
color8='#5e5e74'
color9='#62677B'
color10='#6F758A'
color11='#857C90'
color12='#7C849D'
color13='#8993AF'
color14='#9FAFD8'
color15='#c3c3c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
