[colors.primary]
background = '#11140e'
foreground = '#e1e4d9'

[colors.cursor]
text = '#11140e'
cursor = '#e1e4d9'

[colors.vi_mode_cursor]
text = '#11140e'
cursor = '#acd28f'

[colors.search.matches]
foreground = '#1d211a'
background = '#a0cfce'

[colors.search.focused_match]
foreground = '#1d211a'
background = '#acd28f'

[colors.footer_bar]
foreground = '#1d211a'
background = '#e6e8e3'

[colors.hints.start]
foreground = '#1d211a'
background = '#bdcbaf'

[colors.hints.end]
foreground = '#1d211a'
background = '#bdcbaf'

[colors.selection]
text = '#c4c8bb'
background = '#43483e'


[colors.normal]
black   = '#43483e'
red     = '#ffb4ab'
green   = '#acd28f'
yellow  = '#bdcbaf'
blue    = '#a0cfce'
magenta = '#acd28f'
cyan    = '#bdcbaf'
white   = '#e1e4d9'


[colors.bright]
black   = '#8e9286'
red     = '#ffb4ab'
green   = '#acd28f'
yellow  = '#bdcbaf'
blue    = '#a0cfce'
magenta = '#acd28f'
cyan    = '#bdcbaf'
white   = '#e1e4d9'


[colors.dim]
black   = '#43483e'
red     = '#ffb4ab'
green   = '#acd28f'
yellow  = '#bdcbaf'
blue    = '#a0cfce'
magenta = '#acd28f'
cyan    = '#bdcbaf'
white   = '#e1e4d9'
