[colors.primary]
background = '#131315'
foreground = '#e4e2e4'
 
[colors.cursor]
text = '#e4e2e4'
cursor = '#c6c6ce' 
 
[colors.vi_mode_cursor]
text = '#131315'
cursor = '#bfc5e3' 
 
[colors.search.matches]
foreground = '#45464d' 
background = '#dfbcd5' 
 
[colors.search.focused_match]
foreground = '#45464d' 
background = '#bfc5e3' 
 
[colors.footer_bar]
foreground = '#45464d' 
background = '#e4e2e4' 
 
[colors.hints.start]
foreground = '#45464d' 
background = '#c4c6d3' 
 
[colors.hints.end]
foreground = '#45464d' 
background = '#c4c6d3' 
 
[colors.selection]
text = '#131315'
background = '#bfc5e3'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#bfc5e3' 
yellow = '#565d77' 
blue = '#bfc5e3' 
magenta = '#dfbcd5' 
cyan = '#c4c6d3' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 