general {
    hide_cursor = true
}

background {
    monitor =
    color = rgba(000000ff)
}

label {
    monitor =
    text = $TIME
    font_size = 64
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    position = 0, -80
    halign = center
    valign = center

    outline_thickness = 2
    rounding = 10

    outer_color = rgba(ffffffaa)
    inner_color = rgba(000000aa)
    font_color = rgba(ffffffff)

    placeholder_text = Password...
    fail_text = $FAIL
}
