# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                 CachyOS Hyprland Configuration              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$mainMod = SUPER



# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Source Files                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/decorations.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/layout.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/config/windowrules.conf
source = ~/.config/hypr/config/misc.conf
#source = ~/.config/hypr/config/hyprtask.conf



source = ~/.config/hypr/noctalia/noctalia-colors.conf

# >>> HYPRLAND VISUAL EDITOR START <<<
# 1. Active Uninstall Watchdog
exec-once = /home/kalon/.cache/noctalia/HVE/hve_watchdog.sh
# 2. Variable Definition (Color Palette)
source = /home/kalon/.config/hypr/noctalia/noctalia-colors.conf
# 3. Effects Application (Visual Editor)
source = /home/kalon/.cache/noctalia/HVE/overlay.conf
# >>> HYPRLAND VISUAL EDITOR END <<<
