-- Generated by Noctalia

local primary = "rgb(a2b08d)"
local surface = "rgb(1c1e1a)"
local on_surface = "rgb(f4f6eb)"
local secondary = "rgb(948e74)"
local on_secondary = "rgb(131411)"
local error = "rgb(ce7a71)"
local on_error = "rgb(131411)"
local shadow = "rgb(0a0a09)"

local function apply_theme()
    hl.config({
        general = {
            col = {
                active_border = primary,
                inactive_border = surface,
            },
        },
        decoration = {
            shadow = {
                color = shadow,
            },
            glow = {
                color = shadow,
            },
        },
        group = {
            col = {
                border_active = secondary,
                border_inactive = surface,
                border_locked_active = error,
                border_locked_inactive = surface,
            },

            groupbar = {
                gradients = true,
                col = {
                    active = secondary,
                    inactive = surface,
                    locked_active = error,
                    locked_inactive = surface,
                },
                text_color = on_secondary,
                text_color_inactive = on_surface,
                text_color_locked_active = on_error,
                text_color_locked_inactive = on_surface,
            },
        },
    })
end

return {
    colors = {
        primary = primary,
        surface = surface,
        on_surface = on_surface,
        secondary = secondary,
        on_secondary = on_secondary,
        error = error,
        on_error = on_error,
        shadow = shadow,
    },
    apply_theme = apply_theme
}
