require("config.defaults")

hl.on("hyprland.start", function()
  hl.exec_cmd(_G.shell_daemon)
  hl.exec_cmd("snappy-switcher --daemon")
  
  hl.exec_cmd("fcitx5 -d &")
  hl.exec_cmd("bash -c 'wl-paste --watch cliphist store &'")
  hl.exec_cmd("/usr/lib/mate-polkit/polkit-mate-authentication-agent-1")
  hl.exec_cmd("bash -c 'mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown' &")
  hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1 &")
  hl.exec_cmd("systemctl --user import-environment &")
  hl.exec_cmd("hash dbus-update-activation-environment 2>/dev/null &")
  hl.exec_cmd("dbus-update-activation-environment --systemd &")
  hl.exec_cmd("sleep 2 && sudo /home/kalon/Dotfiles/hypr/.config/hypr/scripts/fix-trackpad-power.sh &")
  hl.exec_cmd("sleep 3 && /home/kalon/Dotfiles/hypr/.config/hypr/scripts/power-management.sh &")
end)
