# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$filemanager = nautilus
$term_filemanager = kitty -e yazi
$editor= code
$music = spotify
$notetaking = obsidian
$browser = chromium
$applauncher =  rofi -show drun
$terminal = ghostty
$idlehandler = hypridle
$capturing = grim -g "$(slurp)" - | swappy -f -
$wallpaper = ~/.config/themes/current/background
