# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

input {
    kb_layout = us
    follow_mouse = 1

    # GLOBAL (this is where these actually work)
    sensitivity = 0.45
    accel_profile = flat
    force_no_accel = false

    touchpad {
        natural_scroll = true
        disable_while_typing = false

        tap-to-click = true
        clickfinger_behavior = false

        scroll_factor = 0.7
    }
}

cursor {
    no_hardware_cursors = false
}

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Gestures Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Disable for lowest latency
# gesture = 3,horizontal , workspace, swipe
# gesture = 4, down, close