# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Layout Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
general {
    layout = dwindle
}

scrolling {
    fullscreen_on_one_column = true
    focus_fit_method = 0
    column_width = 0.6
    explicit_column_widths = 0.3, 0.5, 0.65, 0.8, 0.985, 1.0
    follow_focus = true
}

gestures {
    
    gesture = 4, left,  dispatcher, exec, hyprctl dispatch layoutmsg "move +col"
    gesture = 4, right, dispatcher, exec, hyprctl dispatch layoutmsg "move -col"
}