# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/0.45.0/Configuring/Monitors/
monitor = eDP-1, 1920x1200@60, 0x0, 1



# scaler monitor
# monitor=eDP-1,disable
# monitor=HDMI-A-1,1920x1080@100,0x0,1.0


# # # souvik monitor
# monitor=eDP-1,disable
# monitor=HDMI-A-1,2560x1440@144,0x0,1.0
# # monitor=HDMI-A-1,3840x2160@60,0x0,1.5
