-- hl.config({
--     plugin = {
--         scrolloverview = {
--             gesture_distance = 300, -- how far is the "max" for the gesture
--             scale = 0.85, -- preferred overview scale
--             workspace_gap = 10,
--             layout = "horizontal", -- vertical or horizontal
--             wallpaper = 0, -- 0: global only, 1: per-workspace only, 2: both
--             blur = true, -- blur only the main overview wallpaper

--             shadow = {
--                 enabled = true,
--                 range = 50,
--                 render_power = 3,
--                 color = 0xee1a1a1a,
--             },

--             input = {
--                 scrolling_mode = 1, -- 1 = inverted: scroll up → left, scroll down → right
--             },
--         },
--     },
-- })
