color0 #252722
color1 #ce7a71
color2 #a2b08d
color3 #c7ae81
color4 #6f8796
color5 #b89094
color6 #7cb3a0
color7 #f4f6eb
color8 #343730
color9 #da8e86
color10 #b3c29e
color11 #d6be94
color12 #829cb0
color13 #ca9fa3
color14 #8ec4b2
color15 #fafbfe

cursor                #f4f6eb
cursor_text_color     #252722
background            #1c1e1a
foreground            #f4f6eb
selection_foreground  #131411
selection_background  #a2b08d
active_border_color   #a2b08d
inactive_border_color #252722
url_color             #a2b08d

active_tab_foreground   #131411
active_tab_background   #a2b08d
inactive_tab_foreground #a2b08d
inactive_tab_background #252722
cursor_trail_color      #a2b08d
