color0 #fff9ef
color1 #ba1a1a
color2 #6f5d00
color3 #665e40
color4 #43664e
color5 #e1c54b
color6 #d1c6a1
color7 #1d1b16
color8 #7c7767
color9 #ba1a1a
color10 #6f5d00
color11 #665e40
color12 #43664e
color13 #e1c54b
color14 #d1c6a1
color15 #1d1b16

cursor                #1d1b16
cursor_text_color     #fff9ef
background            #fff9ef
foreground            #1d1b16
selection_foreground  #4b4739
selection_background  #eae2cf
active_border_color   #6f5d00
inactive_border_color #eae2cf
url_color             #6f5d00

active_tab_foreground   #ffffff
active_tab_background   #6f5d00
inactive_tab_foreground #4b4739
inactive_tab_background #eae2cf
cursor_trail_color      #4b4739
