color0 #362f2c
color1 #d25780
color2 #99af6b
color3 #f4a21c
color4 #4e89a2
color5 #d1766e
color6 #20c9cb
color7 #e6d5c2
color8 #5a504c
color9 #d25780
color10 #99af6b
color11 #fcba81
color12 #4e89a2
color13 #ea9875
color14 #20c9cb
color15 #e6d5c2

cursor                #ea9875
cursor_text_color     #171311
background            #171311
foreground            #e6d5c2
selection_foreground  #e6d5c2
selection_background  #2f1e17
active_border_color   #fcba81
inactive_border_color #201b19
url_color             #fcba81

active_tab_foreground   #171311
active_tab_background   #fcba81
inactive_tab_foreground #a09384
inactive_tab_background #201b19
cursor_trail_color      #a09384
