[gestures]
fingerCount = 3
invertDirection = true
mouseMoveModifierKey = "option"
mouseResizeModifierKey = "option"
overviewGestureEnabled = true
overviewGestureFingerCount = 3
scrollEnabled = false
scrollModifierKey = "optionShift"
scrollSensitivity = 5.0
trackpadScrollStyle = "snap"
windowGestureSensitivity = 1.0
windowMoveEnabled = false
windowMoveFingerCount = 4
windowResizeEnabled = false
windowResizeFingerCount = 3
workspaceSwipeAxis = "horizontal"
workspaceSwipeEnabled = true
workspaceSwipeFingerCount = 3
