[overview]
zoom = 1.0

[overview.backdrop]
alpha = 1.0
blue = 0.08
green = 0.05
red = 0.05

[overview.windowBorders]

[overview.windowBorders.hovered]
alpha = 1.0
blue = 1.0
green = 0.6
red = 0.4

[overview.windowBorders.normal]
alpha = 0.5
blue = 0.35
green = 0.3
red = 0.3

[overview.windowBorders.selected]
alpha = 1.0
blue = 0.4
green = 0.8
red = 0.3

