[[workspaces]]
id = "AD36F001-C57E-41A5-AC1D-DF5249D007F0"
layoutType = "dwindle"
name = "1"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "454CECD4-5E9D-4ED1-95D7-979D48817F5F"
layoutType = "dwindle"
name = "2"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "BEB842B5-E894-4791-9FD1-397C3CDD3538"
layoutType = "dwindle"
name = "3"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "248AA883-2261-4D45-943C-79C0E46A232B"
layoutType = "dwindle"
name = "4"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "8B8C45D6-CE9E-41D9-BD50-BE4989D5E3DE"
layoutType = "dwindle"
name = "5"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
displayName = "6"
id = "B4CA4934-4200-4ADA-A697-3D0BABF49535"
layoutType = "dwindle"
name = "6"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "D4BB9B5A-0F4A-4EA8-AE92-72EB2E45D007"
layoutType = "dwindle"
name = "7"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "0E18F6B0-345A-4078-8B21-33641F07A861"
layoutType = "dwindle"
name = "8"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "D4BB9B5A-0F4A-4EA8-AE92-72EB2E45D010"
layoutType = "dwindle"
name = "10"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "8D4D711C-2B2F-4FEC-86BF-FA952037738A"
layoutType = "dwindle"
name = "9"

[workspaces.monitorAssignment]
type = "main"
