color0 #e9f1da
color1 #ad4d3b
color2 #89c022
color3 #3ca329
color4 #2d3e86
color5 #5d8217
color6 #2a7e1b
color7 #1a1b18
color8 #7d9056
color9 #ad4d3b
color10 #89c022
color11 #3ca329
color12 #2d3e86
color13 #5d8217
color14 #2a7e1b
color15 #1a1b18

cursor                #1a1b18
cursor_text_color     #e9f1da
background            #e9f1da
foreground            #1a1b18
selection_foreground  #5b5e55
selection_background  #cfe1ad
active_border_color   #89c022
inactive_border_color #cfe1ad
url_color             #89c022

active_tab_foreground   #25251f
active_tab_background   #89c022
inactive_tab_foreground #5b5e55
inactive_tab_background #cfe1ad
cursor_trail_color      #5b5e55
