color0 #131315
color1 #ffb4ab
color2 #bfc5e3
color3 #c4c6d3
color4 #dfbcd5
color5 #bfc5e3
color6 #c4c6d3
color7 #e4e2e4
color8 #909097
color9 #ffb4ab
color10 #bfc5e3
color11 #c4c6d3
color12 #dfbcd5
color13 #bfc5e3
color14 #c4c6d3
color15 #e4e2e4

cursor                #e4e2e4
cursor_text_color     #131315
background            #131315
foreground            #e4e2e4
selection_foreground  #c6c6ce
selection_background  #45464d
active_border_color   #bfc5e3
inactive_border_color #45464d
url_color             #bfc5e3

active_tab_foreground   #283047
active_tab_background   #bfc5e3
inactive_tab_foreground #c6c6ce
inactive_tab_background #45464d
cursor_trail_color      #c6c6ce
