color0 #121317
color1 #ffb4ab
color2 #eac16d
color3 #bfc5e1
color4 #b4c5ff
color5 #b4c5ff
color6 #bfc5e1
color7 #e3e2e7
color8 #8f909b
color9 #bfc5e1
color10 #6c4f00
color11 #1f1f23
color12 #3e5189
color13 #f6f5ff
color14 #444650
color15 #e3e2e7

cursor #b4c5ff
cursor_text_color #e3e2e7

foreground            #e3e2e7
background            #121317
selection_foreground  #293045
selection_background  #bfc5e1
url_color             #b4c5ff
