color0   #131313
color1   #d65555
color2   #478c46
color3   #9c7756
color4   #4a81b9
color5   #939598
color6   #c3c7cb
color7   #abb2bf
color8   #5c6370
color9   #e57e7e
color10   #558d54
color11   #967b61
color12   #d4dadf
color13   #346a84
color14   #47628e
color15   #ffffff

cursor #e5e2e1
cursor_text_color #c5c6ca

foreground            #e5e2e1
background            #131313
selection_foreground  #2f3032
selection_background  #c6c6c8
url_color             #c3c7cb