color0   #121316
color1   #d65555
color2   #478d46
color3   #ad845f
color4   #4f8bc6
color5   #879eba
color6   #a3caf8
color7   #abb2bf
color8   #5c6370
color9   #e57e7e
color10   #71ba6f
color11   #c6a280
color12   #96c6ff
color13   #4082a1
color14   #4a6794
color15   #ffffff

cursor #e2e2e6
cursor_text_color #c2c7cf

foreground            #e2e2e6
background            #121316
selection_foreground  #243141
selection_background  #b9c8dc
url_color             #a3caf8